
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.hsqldb.test;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.ForeignKey;
import org.jooq.Identity;
//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
@SuppressWarnings({"unchecked"})
public class Keys extends AbstractKeys {

	// IDENTITY definitions 

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.T639NumbersTableRecord, java.lang.Integer> IDENTITY_t_639_numbers_table = createIdentity(org.jooq.mp.hsqldb.test.tables.T639NumbersTable.__T_639_NUMBERS_TABLE, org.jooq.mp.hsqldb.test.tables.T639NumbersTable.__T_639_NUMBERS_TABLE.ID);



    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.T65821Record, java.lang.Integer> IDENTITY_t_658_21 = createIdentity(org.jooq.mp.hsqldb.test.tables.T65821.__T_658_21, org.jooq.mp.hsqldb.test.tables.T65821.__T_658_21.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.T65822Record, java.lang.Integer> IDENTITY_t_658_22 = createIdentity(org.jooq.mp.hsqldb.test.tables.T65822.__T_658_22, org.jooq.mp.hsqldb.test.tables.T65822.__T_658_22.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.T65831Record, java.lang.Long> IDENTITY_t_658_31 = createIdentity(org.jooq.mp.hsqldb.test.tables.T65831.__T_658_31, org.jooq.mp.hsqldb.test.tables.T65831.__T_658_31.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.T65832Record, java.lang.Long> IDENTITY_t_658_32 = createIdentity(org.jooq.mp.hsqldb.test.tables.T65832.__T_658_32, org.jooq.mp.hsqldb.test.tables.T65832.__T_658_32.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.T725LobTestRecord, java.lang.Integer> IDENTITY_t_725_lob_test = createIdentity(org.jooq.mp.hsqldb.test.tables.T725LobTest.__T_725_LOB_TEST, org.jooq.mp.hsqldb.test.tables.T725LobTest.__T_725_LOB_TEST.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.T937Record, java.lang.Integer> IDENTITY_t_937 = createIdentity(org.jooq.mp.hsqldb.test.tables.T937.__T_937, org.jooq.mp.hsqldb.test.tables.T937.__T_937.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.TArraysRecord, java.lang.Integer> IDENTITY_t_arrays = createIdentity(org.jooq.mp.hsqldb.test.tables.TArrays.__T_ARRAYS, org.jooq.mp.hsqldb.test.tables.TArrays.__T_ARRAYS.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.TAuthorRecord, java.lang.Integer> IDENTITY_t_author = createIdentity(org.jooq.mp.hsqldb.test.tables.TAuthor.__T_AUTHOR, org.jooq.mp.hsqldb.test.tables.TAuthor.__T_AUTHOR.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.TBookRecord, java.lang.Integer> IDENTITY_t_book = createIdentity(org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK, org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.TBookDetailsRecord, java.lang.Integer> IDENTITY_t_book_details = createIdentity(org.jooq.mp.hsqldb.test.tables.TBookDetails.__T_BOOK_DETAILS, org.jooq.mp.hsqldb.test.tables.TBookDetails.__T_BOOK_DETAILS.ID);


    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.TBooleansRecord, java.lang.Integer> IDENTITY_t_booleans = createIdentity(org.jooq.mp.hsqldb.test.tables.TBooleans.__T_BOOLEANS, org.jooq.mp.hsqldb.test.tables.TBooleans.__T_BOOLEANS.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.TDatesRecord, java.lang.Integer> IDENTITY_t_dates = createIdentity(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES, org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.TIdentityPkRecord, java.lang.Integer> IDENTITY_t_identity_pk = createIdentity(org.jooq.mp.hsqldb.test.tables.TIdentityPk.__T_IDENTITY_PK, org.jooq.mp.hsqldb.test.tables.TIdentityPk.__T_IDENTITY_PK.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.TLanguageRecord, java.lang.Integer> IDENTITY_t_language = createIdentity(org.jooq.mp.hsqldb.test.tables.TLanguage.__T_LANGUAGE, org.jooq.mp.hsqldb.test.tables.TLanguage.__T_LANGUAGE.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.TTriggersRecord, java.lang.Integer> IDENTITY_t_triggers = createIdentity(org.jooq.mp.hsqldb.test.tables.TTriggers.__T_TRIGGERS, org.jooq.mp.hsqldb.test.tables.TTriggers.__T_TRIGGERS.ID_GENERATED);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.XTestCase6469Record, java.lang.Integer> IDENTITY_x_test_case_64_69 = createIdentity(org.jooq.mp.hsqldb.test.tables.XTestCase6469.__X_TEST_CASE_64_69, org.jooq.mp.hsqldb.test.tables.XTestCase6469.__X_TEST_CASE_64_69.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.XTestCase71Record, java.lang.Integer> IDENTITY_x_test_case_71 = createIdentity(org.jooq.mp.hsqldb.test.tables.XTestCase71.__X_TEST_CASE_71, org.jooq.mp.hsqldb.test.tables.XTestCase71.__X_TEST_CASE_71.ID);

    public static final Identity<org.jooq.mp.hsqldb.test.tables.records.XTestCase85Record, java.lang.Integer> IDENTITY_x_test_case_85 = createIdentity(org.jooq.mp.hsqldb.test.tables.XTestCase85.__X_TEST_CASE_85, org.jooq.mp.hsqldb.test.tables.XTestCase85.__X_TEST_CASE_85.ID);





    // UNIQUE and PRIMARY KEY definitions


























    //Limitation

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.T639NumbersTableRecord> KEY_t_639_numbers_table_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.T639NumbersTable.__T_639_NUMBERS_TABLE,
            org.jooq.mp.hsqldb.test.tables.T639NumbersTable.__T_639_NUMBERS_TABLE.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.T65811Record> KEY_t_658_11_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.T65811.__T_658_11,
            org.jooq.mp.hsqldb.test.tables.T65811.__T_658_11.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.T65812Record> KEY_t_658_12_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.T65812.__T_658_12,
            org.jooq.mp.hsqldb.test.tables.T65812.__T_658_12.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.T65821Record> KEY_t_658_21_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.T65821.__T_658_21,
            org.jooq.mp.hsqldb.test.tables.T65821.__T_658_21.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.T65822Record> KEY_t_658_22_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.T65822.__T_658_22,
            org.jooq.mp.hsqldb.test.tables.T65822.__T_658_22.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.T65831Record> KEY_t_658_31_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.T65831.__T_658_31,
            org.jooq.mp.hsqldb.test.tables.T65831.__T_658_31.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.T65832Record> KEY_t_658_32_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.T65832.__T_658_32,
            org.jooq.mp.hsqldb.test.tables.T65832.__T_658_32.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.T725LobTestRecord> KEY_t_725_lob_test_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.T725LobTest.__T_725_LOB_TEST,
            org.jooq.mp.hsqldb.test.tables.T725LobTest.__T_725_LOB_TEST.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.T937Record> KEY_t_937_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.T937.__T_937,
            org.jooq.mp.hsqldb.test.tables.T937.__T_937.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TArraysRecord> KEY_t_arrays_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TArrays.__T_ARRAYS,
            org.jooq.mp.hsqldb.test.tables.TArrays.__T_ARRAYS.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TAuthorRecord> KEY_t_author_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TAuthor.__T_AUTHOR,
            org.jooq.mp.hsqldb.test.tables.TAuthor.__T_AUTHOR.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TBookRecord> KEY_t_book_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK,
            org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TBookDetailsRecord> KEY_t_book_details_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TBookDetails.__T_BOOK_DETAILS,
            org.jooq.mp.hsqldb.test.tables.TBookDetails.__T_BOOK_DETAILS.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TBookToBookStoreRecord> KEY_t_book_to_book_store_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TBookToBookStore.__T_BOOK_TO_BOOK_STORE,
            org.jooq.mp.hsqldb.test.tables.TBookToBookStore.__T_BOOK_TO_BOOK_STORE.BOOK_STORE_NAME,
            org.jooq.mp.hsqldb.test.tables.TBookToBookStore.__T_BOOK_TO_BOOK_STORE.BOOK_ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TBooleansRecord> KEY_t_booleans_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TBooleans.__T_BOOLEANS,
            org.jooq.mp.hsqldb.test.tables.TBooleans.__T_BOOLEANS.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TDatesRecord> KEY_t_dates_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES,
            org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TIdentityPkRecord> KEY_t_identity_pk_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TIdentityPk.__T_IDENTITY_PK,
            org.jooq.mp.hsqldb.test.tables.TIdentityPk.__T_IDENTITY_PK.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TLanguageRecord> KEY_t_language_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TLanguage.__T_LANGUAGE,
            org.jooq.mp.hsqldb.test.tables.TLanguage.__T_LANGUAGE.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.TTriggersRecord> KEY_t_triggers_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.TTriggers.__T_TRIGGERS,
            org.jooq.mp.hsqldb.test.tables.TTriggers.__T_TRIGGERS.ID_GENERATED        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.XTestCase6469Record> KEY_x_test_case_64_69_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.XTestCase6469.__X_TEST_CASE_64_69,
            org.jooq.mp.hsqldb.test.tables.XTestCase6469.__X_TEST_CASE_64_69.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.XTestCase71Record> KEY_x_test_case_71_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.XTestCase71.__X_TEST_CASE_71,
            org.jooq.mp.hsqldb.test.tables.XTestCase71.__X_TEST_CASE_71.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.XTestCase85Record> KEY_x_test_case_85_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.XTestCase85.__X_TEST_CASE_85,
            org.jooq.mp.hsqldb.test.tables.XTestCase85.__X_TEST_CASE_85.ID        );

    public static final UniqueKey<org.jooq.mp.hsqldb.test.tables.records.XUnusedRecord> KEY_x_unused_PRIMARY= 
        createUniqueKey(org.jooq.mp.hsqldb.test.tables.XUnused.__X_UNUSED,
            org.jooq.mp.hsqldb.test.tables.XUnused.__X_UNUSED.ID,
            org.jooq.mp.hsqldb.test.tables.XUnused.__X_UNUSED.NAME        );




	// FOREIGN KEY definitions












   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.TBookRecord, org.jooq.mp.hsqldb.test.tables.records.TAuthorRecord> fk_t_book_AUTHOR_ID1 = createForeignKey(KEY_t_author_PRIMARY, org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK, org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK.AUTHOR_ID);
   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.TBookRecord, org.jooq.mp.hsqldb.test.tables.records.TAuthorRecord> fk_t_book_CO_AUTHOR_ID1 = createForeignKey(KEY_t_author_PRIMARY, org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK, org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK.CO_AUTHOR_ID);
   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.TBookRecord, org.jooq.mp.hsqldb.test.tables.records.TBookDetailsRecord> fk_t_book_DETAILS_ID1 = createForeignKey(KEY_t_book_details_PRIMARY, org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK, org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK.DETAILS_ID);
   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.TBookRecord, org.jooq.mp.hsqldb.test.tables.records.TLanguageRecord> fk_t_book_LANGUAGE_ID1 = createForeignKey(KEY_t_language_PRIMARY, org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK, org.jooq.mp.hsqldb.test.tables.TBook.__T_BOOK.LANGUAGE_ID);


   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.TBookToBookStoreRecord, org.jooq.mp.hsqldb.test.tables.records.TBookRecord> fk_t_book_to_book_store_BOOK_ID1 = createForeignKey(KEY_t_book_PRIMARY, org.jooq.mp.hsqldb.test.tables.TBookToBookStore.__T_BOOK_TO_BOOK_STORE, org.jooq.mp.hsqldb.test.tables.TBookToBookStore.__T_BOOK_TO_BOOK_STORE.BOOK_ID);
   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.TBookToBookStoreRecord, org.jooq.mp.hsqldb.test.tables.records.TBookStoreRecord> fk_t_book_to_book_store_BOOK_STORE_NAME1 = createForeignKey(KEY_t_book_store_PRIMARY, org.jooq.mp.hsqldb.test.tables.TBookToBookStore.__T_BOOK_TO_BOOK_STORE, org.jooq.mp.hsqldb.test.tables.TBookToBookStore.__T_BOOK_TO_BOOK_STORE.BOOK_STORE_NAME);






   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.XTestCase6469Record, org.jooq.mp.hsqldb.test.tables.records.XUnusedRecord> fk_x_test_case_64_69_UNUSED_ID1 = createForeignKey(KEY_x_unused_PRIMARY, org.jooq.mp.hsqldb.test.tables.XTestCase6469.__X_TEST_CASE_64_69, org.jooq.mp.hsqldb.test.tables.XTestCase6469.__X_TEST_CASE_64_69.UNUSED_ID);

   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.XTestCase71Record, org.jooq.mp.hsqldb.test.tables.records.XTestCase6469Record> fk_x_test_case_71_TEST_CASE_64_69_ID1 = createForeignKey(KEY_x_test_case_64_69_PRIMARY, org.jooq.mp.hsqldb.test.tables.XTestCase71.__X_TEST_CASE_71, org.jooq.mp.hsqldb.test.tables.XTestCase71.__X_TEST_CASE_71.TEST_CASE_64_69_ID);

   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.XTestCase85Record, org.jooq.mp.hsqldb.test.tables.records.XUnusedRecord> fk_x_test_case_85_X_UNUSED_ID1 = createForeignKey(KEY_x_unused_PRIMARY, org.jooq.mp.hsqldb.test.tables.XTestCase85.__X_TEST_CASE_85, org.jooq.mp.hsqldb.test.tables.XTestCase85.__X_TEST_CASE_85.X_UNUSED_ID);

   	public static final ForeignKey<org.jooq.mp.hsqldb.test.tables.records.XUnusedRecord, org.jooq.mp.hsqldb.test.tables.records.XUnusedRecord> fk_x_unused_ID_REF1 = createForeignKey(KEY_x_unused_PRIMARY, org.jooq.mp.hsqldb.test.tables.XUnused.__X_UNUSED, org.jooq.mp.hsqldb.test.tables.XUnused.__X_UNUSED.ID_REF);




	/**
	 * No instances
	 */
	private Keys() {}

//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	
}
