
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.hsqldb.test;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.ForeignKey;
import org.jooq.Identity;
//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
/**
 * Convenience access to all stored procedures and functions in test
 *
 * This class is generated by jOOQ
 */

public final class Routines {

	/**
	 * Invoke store proc
	 *
	 * @throws org.jooq.exception.DataAccessException if something went wrong executing the query
	 */


	/**
	 * No instances
	 */
	private Routines() {}
}
