
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.mysql.test.tables.records;

import org.jooq.impl.UpdatableRecordImpl;

import org.jooq.mp.mysql.test.tables.TBooleans;
import org.jooq.mp.mysql.test.Test;
import org.jooq.mp.mysql.test.Keys;
import java.sql.*;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class TBooleansRecord extends UpdatableRecordImpl<org.jooq.mp.mysql.test.tables.records.TBooleansRecord> {

	private static final long serialVersionUID = 123456789;

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-pk-test@
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public void setId(java.lang.Integer value) {
        setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.ID, value);
    }
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public java.lang.Integer getId() {
        return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.ID);
    }
//MP-MANAGED-UPDATABLE-ENDING
//many2many

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.ONE_ZERO-test@
	/**
	 * mapping one_zero setter
	 */
	public void setOneZero(java.lang.Integer value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.ONE_ZERO, value);
	}
	
	/**
	 * mapping one_zero getter
	 */
	public java.lang.Integer getOneZero() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.ONE_ZERO);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.TRUE_FALSE_LC-test@
	/**
	 * mapping true_false_lc setter
	 */
	public void setTrueFalseLc(java.lang.String value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.TRUE_FALSE_LC, value);
	}
	
	/**
	 * mapping true_false_lc getter
	 */
	public java.lang.String getTrueFalseLc() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.TRUE_FALSE_LC);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.TRUE_FALSE_UC-test@
	/**
	 * mapping true_false_uc setter
	 */
	public void setTrueFalseUc(java.lang.String value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.TRUE_FALSE_UC, value);
	}
	
	/**
	 * mapping true_false_uc getter
	 */
	public java.lang.String getTrueFalseUc() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.TRUE_FALSE_UC);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.YES_NO_LC-test@
	/**
	 * mapping yes_no_lc setter
	 */
	public void setYesNoLc(java.lang.String value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.YES_NO_LC, value);
	}
	
	/**
	 * mapping yes_no_lc getter
	 */
	public java.lang.String getYesNoLc() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.YES_NO_LC);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.YES_NO_UC-test@
	/**
	 * mapping yes_no_uc setter
	 */
	public void setYesNoUc(java.lang.String value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.YES_NO_UC, value);
	}
	
	/**
	 * mapping yes_no_uc getter
	 */
	public java.lang.String getYesNoUc() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.YES_NO_UC);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.Y_N_LC-test@
	/**
	 * mapping y_n_lc setter
	 */
	public void setYNLc(java.lang.String value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.Y_N_LC, value);
	}
	
	/**
	 * mapping y_n_lc getter
	 */
	public java.lang.String getYNLc() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.Y_N_LC);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.Y_N_UC-test@
	/**
	 * mapping y_n_uc setter
	 */
	public void setYNUc(java.lang.String value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.Y_N_UC, value);
	}
	
	/**
	 * mapping y_n_uc getter
	 */
	public java.lang.String getYNUc() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.Y_N_UC);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.VC_BOOLEAN-test@
	/**
	 * mapping vc_boolean setter
	 */
	public void setVcBoolean(java.lang.String value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.VC_BOOLEAN, value);
	}
	
	/**
	 * mapping vc_boolean getter
	 */
	public java.lang.String getVcBoolean() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.VC_BOOLEAN);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.C_BOOLEAN-test@
	/**
	 * mapping c_boolean setter
	 */
	public void setCBoolean(java.lang.String value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.C_BOOLEAN, value);
	}
	
	/**
	 * mapping c_boolean getter
	 */
	public java.lang.String getCBoolean() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.C_BOOLEAN);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.N_BOOLEAN-test@
	/**
	 * mapping n_boolean setter
	 */
	public void setNBoolean(java.lang.Integer value) {
		setValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.N_BOOLEAN, value);
	}
	
	/**
	 * mapping n_boolean getter
	 */
	public java.lang.Integer getNBoolean() {
		return getValue(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS.N_BOOLEAN);
	}
	
//MP-MANAGED-UPDATABLE-ENDING

	/**
	 * Create a detached TBooleansRecord
	 */
	public TBooleansRecord() {
		super(org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS);
	}

//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@

}
