
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.oracle.test.tables.records;

import org.jooq.impl.UpdatableRecordImpl;

import org.jooq.mp.oracle.test.tables.T976;
import org.jooq.mp.oracle.test.Test;
import org.jooq.mp.oracle.test.Keys;
import java.sql.*;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class T976Record extends UpdatableRecordImpl<org.jooq.mp.oracle.test.tables.records.T976Record> {

	private static final long serialVersionUID = 123456789;

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-pk-test@
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public void setId(java.lang.Long value) {
        setValue(org.jooq.mp.oracle.test.tables.T976.__T_976.ID, value);
    }
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public java.lang.Long getId() {
        return getValue(org.jooq.mp.oracle.test.tables.T976.__T_976.ID);
    }
//MP-MANAGED-UPDATABLE-ENDING
//many2many

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.oracle.test.tables.T976.__T_976.D-test@
	/**
	 * mapping D setter
	 */
	public void setD(java.sql.Timestamp value) {
		setValue(org.jooq.mp.oracle.test.tables.T976.__T_976.D, value);
	}
	
	/**
	 * mapping D getter
	 */
	public java.sql.Timestamp getD() {
		return getValue(org.jooq.mp.oracle.test.tables.T976.__T_976.D);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.oracle.test.tables.T976.__T_976.T-test@
	/**
	 * mapping T setter
	 */
	public void setT(java.lang.String value) {
		setValue(org.jooq.mp.oracle.test.tables.T976.__T_976.T, value);
	}
	
	/**
	 * mapping T getter
	 */
	public java.lang.String getT() {
		return getValue(org.jooq.mp.oracle.test.tables.T976.__T_976.T);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.oracle.test.tables.T976.__T_976.O-test@
	/**
	 * mapping O setter
	 */
	public void setO(java.lang.String value) {
		setValue(org.jooq.mp.oracle.test.tables.T976.__T_976.O, value);
	}
	
	/**
	 * mapping O getter
	 */
	public java.lang.String getO() {
		return getValue(org.jooq.mp.oracle.test.tables.T976.__T_976.O);
	}
	
//MP-MANAGED-UPDATABLE-ENDING

	/**
	 * Create a detached T976Record
	 */
	public T976Record() {
		super(org.jooq.mp.oracle.test.tables.T976.__T_976);
	}

//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@

}
