
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.oracle.test.tables.records;

import org.jooq.impl.UpdatableRecordImpl;

import org.jooq.mp.oracle.test.tables.TBookDetails;
import org.jooq.mp.oracle.test.Test;
import org.jooq.mp.oracle.test.Keys;
import java.sql.*;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class TBookDetailsRecord extends UpdatableRecordImpl<org.jooq.mp.oracle.test.tables.records.TBookDetailsRecord> {

	private static final long serialVersionUID = 123456789;

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-pk-test@
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public void setId(java.lang.Long value) {
        setValue(org.jooq.mp.oracle.test.tables.TBookDetails.__T_BOOK_DETAILS.ID, value);
    }
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public java.lang.Long getId() {
        return getValue(org.jooq.mp.oracle.test.tables.TBookDetails.__T_BOOK_DETAILS.ID);
    }
//MP-MANAGED-UPDATABLE-ENDING
  //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-child-TBooks-test@
	/**
	 * An uncommented item
	 * 
	 */
	public java.util.List<org.jooq.mp.oracle.test.tables.records.TBookRecord> fetchTBooksList() {
		return create()
			.selectFrom(org.jooq.mp.oracle.test.tables.TBook.__T_BOOK)
			.where(org.jooq.mp.oracle.test.tables.TBook.__T_BOOK.DETAILS_ID.equal(getValue(org.jooq.mp.oracle.test.tables.TBookDetails.__T_BOOK_DETAILS.ID))) 
			.fetch();
	}
	
//MP-MANAGED-UPDATABLE-ENDING
//many2many


	/**
	 * Create a detached TBookDetailsRecord
	 */
	public TBookDetailsRecord() {
		super(org.jooq.mp.oracle.test.tables.TBookDetails.__T_BOOK_DETAILS);
	}

//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@

}
