
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.oracle.test.tables.records;

import org.jooq.impl.UpdatableRecordImpl;

import org.jooq.mp.oracle.test.tables.TDirectory;
import org.jooq.mp.oracle.test.Test;
import org.jooq.mp.oracle.test.Keys;
import java.sql.*;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class TDirectoryRecord extends UpdatableRecordImpl<org.jooq.mp.oracle.test.tables.records.TDirectoryRecord> {

	private static final long serialVersionUID = 123456789;

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-pk-test@
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public void setId(java.lang.Long value) {
        setValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.ID, value);
    }
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public java.lang.Long getId() {
        return getValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.ID);
    }
//MP-MANAGED-UPDATABLE-ENDING
  //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-child-TDirectories-test@
	/**
	 * An uncommented item
	 * 
	 */
	public java.util.List<org.jooq.mp.oracle.test.tables.records.TDirectoryRecord> fetchTDirectoriesList() {
		return create()
			.selectFrom(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY)
			.where(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.PARENT_ID.equal(getValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.ID))) 
			.fetch();
	}
	
//MP-MANAGED-UPDATABLE-ENDING
//many2many

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.IS_DIRECTORY-test@
	/**
	 * mapping IS_DIRECTORY setter
	 */
	public void setIsDirectory(java.lang.Long value) {
		setValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.IS_DIRECTORY, value);
	}
	
	/**
	 * mapping IS_DIRECTORY getter
	 */
	public java.lang.Long getIsDirectory() {
		return getValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.IS_DIRECTORY);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.NAME-test@
	/**
	 * mapping name setter
	 */
	public void setName(java.lang.String value) {
		setValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.NAME, value);
	}
	
	/**
	 * mapping name getter
	 */
	public java.lang.String getName() {
		return getValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.NAME);
	}
	
//MP-MANAGED-UPDATABLE-ENDING

   //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-parent-org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.PARENT_ID-test@
	/**
	 * setter and mapper in for parentId
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [TDirectory.parentId]
	 * REFERENCES TDirectory [TDirectory.id]
	 * </pre></code>
	 */
	public void setParentId(java.lang.Long value) {
		setValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.PARENT_ID, value);
	}
	

	/**
	 * getter and mapper out for parentId
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [TDirectory.parentId]
	 * REFERENCES TDirectory [TDirectory.id]
	 * </pre></code>
	 */
	public java.lang.Long getParentId() {
		return getValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.PARENT_ID);
	}
	

	/**
	 * fetcher of associated TDirectory via ParentId
	 * <p>
	 * <code><pre>
     * FOREIGN KEY [TDirectory.parentId]
     * REFERENCES TDirectory [TDirectory.id]
	 * </pre></code>
	 */
	public org.jooq.mp.oracle.test.tables.records.TDirectoryRecord fetchParentId() {
		return create()
			.selectFrom(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY)
			.where(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.ID.equal(getValue(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY.PARENT_ID))) //ID
			.fetchOne();
    }
//MP-MANAGED-UPDATABLE-ENDING
	/**
	 * Create a detached TDirectoryRecord
	 */
	public TDirectoryRecord() {
		super(org.jooq.mp.oracle.test.tables.TDirectory.__T_DIRECTORY);
	}

//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@

}
