
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.oracle.test.tables.records;

import org.jooq.impl.UpdatableRecordImpl;

import org.jooq.mp.oracle.test.tables.XTestCase6469;
import org.jooq.mp.oracle.test.Test;
import org.jooq.mp.oracle.test.Keys;
import java.sql.*;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class XTestCase6469Record extends UpdatableRecordImpl<org.jooq.mp.oracle.test.tables.records.XTestCase6469Record> {

	private static final long serialVersionUID = 123456789;

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-pk-test@
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public void setId(java.lang.Long value) {
        setValue(org.jooq.mp.oracle.test.tables.XTestCase6469.__X_TEST_CASE_64_69.ID, value);
    }
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public java.lang.Long getId() {
        return getValue(org.jooq.mp.oracle.test.tables.XTestCase6469.__X_TEST_CASE_64_69.ID);
    }
//MP-MANAGED-UPDATABLE-ENDING
  //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-child-XTestCase71s-test@
	/**
	 * An uncommented item
	 * 
	 */
	public java.util.List<org.jooq.mp.oracle.test.tables.records.XTestCase71Record> fetchXTestCase71sList() {
		return create()
			.selectFrom(org.jooq.mp.oracle.test.tables.XTestCase71.__X_TEST_CASE_71)
			.where(org.jooq.mp.oracle.test.tables.XTestCase71.__X_TEST_CASE_71.TEST_CASE_64_69_ID.equal(getValue(org.jooq.mp.oracle.test.tables.XTestCase6469.__X_TEST_CASE_64_69.ID))) 
			.fetch();
	}
	
//MP-MANAGED-UPDATABLE-ENDING
//many2many

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.oracle.test.tables.XTestCase6469.__X_TEST_CASE_64_69.UNUSED_ID-test@
	/**
	 * mapping UNUSED_ID setter
	 */
	public void setUnusedId(java.lang.Long value) {
		setValue(org.jooq.mp.oracle.test.tables.XTestCase6469.__X_TEST_CASE_64_69.UNUSED_ID, value);
	}
	
	/**
	 * mapping UNUSED_ID getter
	 */
	public java.lang.Long getUnusedId() {
		return getValue(org.jooq.mp.oracle.test.tables.XTestCase6469.__X_TEST_CASE_64_69.UNUSED_ID);
	}
	
//MP-MANAGED-UPDATABLE-ENDING

	/**
	 * Create a detached XTestCase6469Record
	 */
	public XTestCase6469Record() {
		super(org.jooq.mp.oracle.test.tables.XTestCase6469.__X_TEST_CASE_64_69);
	}

//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@

}
