
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.derby.test.tables;

import org.jooq.mp.derby.test.tables.records.TBookDetailsRecord;
import org.jooq.mp.derby.test.Test;
import org.jooq.mp.derby.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class TBookDetails extends org.jooq.impl.UpdatableTableImpl <TBookDetailsRecord> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of TBookDetails
	 */
	public static final TBookDetails __T_BOOK_DETAILS = new TBookDetails();

	/**
	 * The class holding records for this type
	 */
	private static final Class<TBookDetailsRecord> __RECORD_TYPE = TBookDetailsRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TBookDetailsRecord> getRecordType() {
		return __RECORD_TYPE;
	}


 
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY ID
	 */
	public final TableField<TBookDetailsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);



	/**
	 * No further instances allowed
	 */
	private TBookDetails() {
		super("T_BOOK_DETAILS", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private TBookDetails(String alias) {
		super(alias, Test.TEST, TBookDetails.__T_BOOK_DETAILS);
	}

	@Override
	public org.jooq.UniqueKey<TBookDetailsRecord> getMainKey() {
		return Keys.KEY_t_book_details_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<UniqueKey<TBookDetailsRecord>> getKeys() {
		return java.util.Arrays.<UniqueKey<TBookDetailsRecord>>asList(Keys.KEY_t_book_details_PRIMARY);
	}

	@Override
	public TBookDetails as(java.lang.String alias) {
		return new TBookDetails(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
