
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.derby.test.tables;

import org.jooq.mp.derby.test.tables.records.XTestCase71Record;
import org.jooq.mp.derby.test.Test;
import org.jooq.mp.derby.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class XTestCase71 extends org.jooq.impl.UpdatableTableImpl <XTestCase71Record> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of XTestCase71
	 */
	public static final XTestCase71 __X_TEST_CASE_71 = new XTestCase71();

	/**
	 * The class holding records for this type
	 */
	private static final Class<XTestCase71Record> __RECORD_TYPE = XTestCase71Record.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<XTestCase71Record> getRecordType() {
		return __RECORD_TYPE;
	}


 
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY ID
	 */
	public final TableField<XTestCase71Record, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);


   	/**
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [XTestCase71.testCase6469Id]
	 * REFERENCES XTestCase6469 [XTestCase6469.id]
	 * </pre></code>
	 */
	public final TableField<XTestCase71Record, java.lang.Integer> TEST_CASE_64_69_ID = createField("TEST_CASE_64_69_ID", org.jooq.impl.SQLDataType.INTEGER, this);


	/**
	 * No further instances allowed
	 */
	private XTestCase71() {
		super("X_TEST_CASE_71", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private XTestCase71(String alias) {
		super(alias, Test.TEST, XTestCase71.__X_TEST_CASE_71);
	}

	@Override
	public org.jooq.UniqueKey<XTestCase71Record> getMainKey() {
		return Keys.KEY_x_test_case_71_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<UniqueKey<XTestCase71Record>> getKeys() {
		return java.util.Arrays.<UniqueKey<XTestCase71Record>>asList(Keys.KEY_x_test_case_71_PRIMARY);
	}

	@Override
	public XTestCase71 as(java.lang.String alias) {
		return new XTestCase71(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
