
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.oracle.test.tables;

import org.jooq.mp.oracle.test.tables.records.T976Record;
import org.jooq.mp.oracle.test.Test;
import org.jooq.mp.oracle.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class T976 extends org.jooq.impl.UpdatableTableImpl <T976Record> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of T976
	 */
	public static final T976 __T_976 = new T976();

	/**
	 * The class holding records for this type
	 */
	private static final Class<T976Record> __RECORD_TYPE = T976Record.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<T976Record> getRecordType() {
		return __RECORD_TYPE;
	}


 
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY ID
	 */
	public final TableField<T976Record, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT, this);

 	/**
	 * D mapping for D
	 */
	public final TableField<T976Record, java.sql.Timestamp> D = createField("D", org.jooq.impl.SQLDataType.TIMESTAMP, this);
 	/**
	 * T mapping for T
	 */
	public final TableField<T976Record, java.lang.String> T = createField("T", org.jooq.impl.SQLDataType.OTHER, this);
 	/**
	 * O mapping for O
	 */
	public final TableField<T976Record, java.lang.String> O = createField("O", org.jooq.impl.SQLDataType.OTHER, this);


	/**
	 * No further instances allowed
	 */
	private T976() {
		super("T_976", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private T976(String alias) {
		super(alias, Test.TEST, T976.__T_976);
	}

	@Override
	public org.jooq.UniqueKey<T976Record> getMainKey() {
		return Keys.KEY_t_976_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<UniqueKey<T976Record>> getKeys() {
		return java.util.Arrays.<UniqueKey<T976Record>>asList(Keys.KEY_t_976_PRIMARY);
	}

	@Override
	public T976 as(java.lang.String alias) {
		return new T976(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
