
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.oracle.test.tables;

import org.jooq.mp.oracle.test.tables.records.TDirectoryRecord;
import org.jooq.mp.oracle.test.Test;
import org.jooq.mp.oracle.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class TDirectory extends org.jooq.impl.UpdatableTableImpl <TDirectoryRecord> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of TDirectory
	 */
	public static final TDirectory __T_DIRECTORY = new TDirectory();

	/**
	 * The class holding records for this type
	 */
	private static final Class<TDirectoryRecord> __RECORD_TYPE = TDirectoryRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TDirectoryRecord> getRecordType() {
		return __RECORD_TYPE;
	}


 
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY ID
	 */
	public final TableField<TDirectoryRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT, this);

 	/**
	 * IS_DIRECTORY mapping for IS_DIRECTORY
	 */
	public final TableField<TDirectoryRecord, java.lang.Long> IS_DIRECTORY = createField("IS_DIRECTORY", org.jooq.impl.SQLDataType.BIT, this);
 	/**
	 * NAME mapping for name
	 */
	public final TableField<TDirectoryRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

   	/**
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [TDirectory.parentId]
	 * REFERENCES TDirectory [TDirectory.id]
	 * </pre></code>
	 */
	public final TableField<TDirectoryRecord, java.lang.Long> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.BIGINT, this);


	/**
	 * No further instances allowed
	 */
	private TDirectory() {
		super("T_DIRECTORY", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private TDirectory(String alias) {
		super(alias, Test.TEST, TDirectory.__T_DIRECTORY);
	}

	@Override
	public org.jooq.UniqueKey<TDirectoryRecord> getMainKey() {
		return Keys.KEY_t_directory_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<UniqueKey<TDirectoryRecord>> getKeys() {
		return java.util.Arrays.<UniqueKey<TDirectoryRecord>>asList(Keys.KEY_t_directory_PRIMARY);
	}

	@Override
	public TDirectory as(java.lang.String alias) {
		return new TDirectory(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
