
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.oracle.test.tables;

import org.jooq.mp.oracle.test.tables.records.VBookRecord;
import org.jooq.mp.oracle.test.Test;
import org.jooq.mp.oracle.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class VBook extends org.jooq.impl.UpdatableTableImpl <VBookRecord> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of VBook
	 */
	public static final VBook __V_BOOK = new VBook();

	/**
	 * The class holding records for this type
	 */
	private static final Class<VBookRecord> __RECORD_TYPE = VBookRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VBookRecord> getRecordType() {
		return __RECORD_TYPE;
	}



 	/**
	 * ID mapping for ID
	 */
	public final TableField<VBookRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT, this);
 	/**
	 * AUTHOR_ID mapping for AUTHOR_ID
	 */
	public final TableField<VBookRecord, java.lang.Long> AUTHOR_ID = createField("AUTHOR_ID", org.jooq.impl.SQLDataType.BIGINT, this);
 	/**
	 * CO_AUTHOR_ID mapping for CO_AUTHOR_ID
	 */
	public final TableField<VBookRecord, java.lang.Long> CO_AUTHOR_ID = createField("CO_AUTHOR_ID", org.jooq.impl.SQLDataType.BIGINT, this);
 	/**
	 * DETAILS_ID mapping for DETAILS_ID
	 */
	public final TableField<VBookRecord, java.lang.Long> DETAILS_ID = createField("DETAILS_ID", org.jooq.impl.SQLDataType.BIGINT, this);
 	/**
	 * TITLE mapping for TITLE
	 */
	public final TableField<VBookRecord, java.lang.String> TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR, this);
 	/**
	 * PUBLISHED_IN mapping for PUBLISHED_IN
	 */
	public final TableField<VBookRecord, java.lang.Long> PUBLISHED_IN = createField("PUBLISHED_IN", org.jooq.impl.SQLDataType.BIGINT, this);
 	/**
	 * LANGUAGE_ID mapping for LANGUAGE_ID
	 */
	public final TableField<VBookRecord, java.lang.Long> LANGUAGE_ID = createField("LANGUAGE_ID", org.jooq.impl.SQLDataType.BIGINT, this);
 	/**
	 * CONTENT_TEXT mapping for CONTENT_TEXT
	 */
	public final TableField<VBookRecord, java.sql.Clob> CONTENT_TEXT = createField("CONTENT_TEXT", org.jooq.impl.SQLDataType.CLOB, this);
 	/**
	 * CONTENT_PDF mapping for CONTENT_PDF
	 */
	public final TableField<VBookRecord, byte[]> CONTENT_PDF = createField("CONTENT_PDF", org.jooq.impl.SQLDataType.BLOB, this);


	/**
	 * No further instances allowed
	 */
	private VBook() {
		super("V_BOOK", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private VBook(String alias) {
		super(alias, Test.TEST, VBook.__V_BOOK);
	}

	@Override
	public VBook as(java.lang.String alias) {
		return new VBook(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
