
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.oracle.test.tables;

import org.jooq.mp.oracle.test.tables.records.VIncompleteRecord;
import org.jooq.mp.oracle.test.Test;
import org.jooq.mp.oracle.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class VIncomplete extends org.jooq.impl.UpdatableTableImpl <VIncompleteRecord> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of VIncomplete
	 */
	public static final VIncomplete __V_INCOMPLETE = new VIncomplete();

	/**
	 * The class holding records for this type
	 */
	private static final Class<VIncompleteRecord> __RECORD_TYPE = VIncompleteRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VIncompleteRecord> getRecordType() {
		return __RECORD_TYPE;
	}



 	/**
	 * ID mapping for ID
	 */
	public final TableField<VIncompleteRecord, java.lang.String> ID = createField("ID", org.jooq.impl.SQLDataType.OTHER, this);
 	/**
	 * AUTHOR_ID mapping for AUTHOR_ID
	 */
	public final TableField<VIncompleteRecord, java.lang.String> AUTHOR_ID = createField("AUTHOR_ID", org.jooq.impl.SQLDataType.OTHER, this);
 	/**
	 * CO_AUTHOR_ID mapping for CO_AUTHOR_ID
	 */
	public final TableField<VIncompleteRecord, java.lang.String> CO_AUTHOR_ID = createField("CO_AUTHOR_ID", org.jooq.impl.SQLDataType.OTHER, this);
 	/**
	 * DETAILS_ID mapping for DETAILS_ID
	 */
	public final TableField<VIncompleteRecord, java.lang.String> DETAILS_ID = createField("DETAILS_ID", org.jooq.impl.SQLDataType.OTHER, this);
 	/**
	 * TITLE mapping for TITLE
	 */
	public final TableField<VIncompleteRecord, java.lang.String> TITLE = createField("TITLE", org.jooq.impl.SQLDataType.OTHER, this);
 	/**
	 * PUBLISHED_IN mapping for PUBLISHED_IN
	 */
	public final TableField<VIncompleteRecord, java.lang.String> PUBLISHED_IN = createField("PUBLISHED_IN", org.jooq.impl.SQLDataType.OTHER, this);
 	/**
	 * LANGUAGE_ID mapping for LANGUAGE_ID
	 */
	public final TableField<VIncompleteRecord, java.lang.String> LANGUAGE_ID = createField("LANGUAGE_ID", org.jooq.impl.SQLDataType.OTHER, this);
 	/**
	 * CONTENT_TEXT mapping for CONTENT_TEXT
	 */
	public final TableField<VIncompleteRecord, java.lang.String> CONTENT_TEXT = createField("CONTENT_TEXT", org.jooq.impl.SQLDataType.OTHER, this);
 	/**
	 * CONTENT_PDF mapping for CONTENT_PDF
	 */
	public final TableField<VIncompleteRecord, java.lang.String> CONTENT_PDF = createField("CONTENT_PDF", org.jooq.impl.SQLDataType.OTHER, this);


	/**
	 * No further instances allowed
	 */
	private VIncomplete() {
		super("V_INCOMPLETE", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private VIncomplete(String alias) {
		super(alias, Test.TEST, VIncomplete.__V_INCOMPLETE);
	}

	@Override
	public VIncomplete as(java.lang.String alias) {
		return new VIncomplete(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
