
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.mysql.test;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public final class Tables {


     public static org.jooq.mp.mysql.test.tables.T639NumbersTable __T_639_NUMBERS_TABLE = org.jooq.mp.mysql.test.tables.T639NumbersTable.__T_639_NUMBERS_TABLE;


     public static org.jooq.mp.mysql.test.tables.T65811 __T_658_11 = org.jooq.mp.mysql.test.tables.T65811.__T_658_11;


     public static org.jooq.mp.mysql.test.tables.T65812 __T_658_12 = org.jooq.mp.mysql.test.tables.T65812.__T_658_12;


     public static org.jooq.mp.mysql.test.tables.T65821 __T_658_21 = org.jooq.mp.mysql.test.tables.T65821.__T_658_21;


     public static org.jooq.mp.mysql.test.tables.T65822 __T_658_22 = org.jooq.mp.mysql.test.tables.T65822.__T_658_22;


     public static org.jooq.mp.mysql.test.tables.T65831 __T_658_31 = org.jooq.mp.mysql.test.tables.T65831.__T_658_31;


     public static org.jooq.mp.mysql.test.tables.T65832 __T_658_32 = org.jooq.mp.mysql.test.tables.T65832.__T_658_32;


     public static org.jooq.mp.mysql.test.tables.T725LobTest __T_725_LOB_TEST = org.jooq.mp.mysql.test.tables.T725LobTest.__T_725_LOB_TEST;


     public static org.jooq.mp.mysql.test.tables.TAuthor __T_AUTHOR = org.jooq.mp.mysql.test.tables.TAuthor.__T_AUTHOR;


     public static org.jooq.mp.mysql.test.tables.TBook __T_BOOK = org.jooq.mp.mysql.test.tables.TBook.__T_BOOK;


     public static org.jooq.mp.mysql.test.tables.TBookDetails __T_BOOK_DETAILS = org.jooq.mp.mysql.test.tables.TBookDetails.__T_BOOK_DETAILS;


     public static org.jooq.mp.mysql.test.tables.TBookToBookStore __T_BOOK_TO_BOOK_STORE = org.jooq.mp.mysql.test.tables.TBookToBookStore.__T_BOOK_TO_BOOK_STORE;


     public static org.jooq.mp.mysql.test.tables.TBooleans __T_BOOLEANS = org.jooq.mp.mysql.test.tables.TBooleans.__T_BOOLEANS;


     public static org.jooq.mp.mysql.test.tables.TDates __T_DATES = org.jooq.mp.mysql.test.tables.TDates.__T_DATES;


     public static org.jooq.mp.mysql.test.tables.TIdentityPk __T_IDENTITY_PK = org.jooq.mp.mysql.test.tables.TIdentityPk.__T_IDENTITY_PK;


     public static org.jooq.mp.mysql.test.tables.TLanguage __T_LANGUAGE = org.jooq.mp.mysql.test.tables.TLanguage.__T_LANGUAGE;


     public static org.jooq.mp.mysql.test.tables.TTriggers __T_TRIGGERS = org.jooq.mp.mysql.test.tables.TTriggers.__T_TRIGGERS;


     public static org.jooq.mp.mysql.test.tables.XTestCase6469 __X_TEST_CASE_64_69 = org.jooq.mp.mysql.test.tables.XTestCase6469.__X_TEST_CASE_64_69;


     public static org.jooq.mp.mysql.test.tables.XTestCase71 __X_TEST_CASE_71 = org.jooq.mp.mysql.test.tables.XTestCase71.__X_TEST_CASE_71;


     public static org.jooq.mp.mysql.test.tables.XTestCase85 __X_TEST_CASE_85 = org.jooq.mp.mysql.test.tables.XTestCase85.__X_TEST_CASE_85;


     public static org.jooq.mp.mysql.test.tables.XUnused __X_UNUSED = org.jooq.mp.mysql.test.tables.XUnused.__X_UNUSED;





	/**
	 * No instances
	 */
	private Tables() {}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	
}
