
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.hsqldb.test.tables.records;

import org.jooq.impl.UpdatableRecordImpl;

import org.jooq.mp.hsqldb.test.tables.TDates;
import org.jooq.mp.hsqldb.test.Test;
import org.jooq.mp.hsqldb.test.Keys;
import java.sql.*;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class TDatesRecord extends UpdatableRecordImpl<org.jooq.mp.hsqldb.test.tables.records.TDatesRecord> {

	private static final long serialVersionUID = 123456789;

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-pk-test@
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public void setId(java.lang.Integer value) {
        setValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.ID, value);
    }
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public java.lang.Integer getId() {
        return getValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.ID);
    }
//MP-MANAGED-UPDATABLE-ENDING
//many2many

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.D-test@
	/**
	 * mapping D setter
	 */
	public void setD(java.sql.Date value) {
		setValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.D, value);
	}
	
	/**
	 * mapping D getter
	 */
	public java.sql.Date getD() {
		return getValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.D);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.T-test@
	/**
	 * mapping T setter
	 */
	public void setT(java.sql.Timestamp value) {
		setValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.T, value);
	}
	
	/**
	 * mapping T getter
	 */
	public java.sql.Timestamp getT() {
		return getValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.T);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.TS-test@
	/**
	 * mapping TS setter
	 */
	public void setTs(java.sql.Timestamp value) {
		setValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.TS, value);
	}
	
	/**
	 * mapping TS getter
	 */
	public java.sql.Timestamp getTs() {
		return getValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.TS);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.D_INT-test@
	/**
	 * mapping D_INT setter
	 */
	public void setDInt(java.lang.Integer value) {
		setValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.D_INT, value);
	}
	
	/**
	 * mapping D_INT getter
	 */
	public java.lang.Integer getDInt() {
		return getValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.D_INT);
	}
	
//MP-MANAGED-UPDATABLE-ENDING
 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.TS_BIGINT-test@
	/**
	 * mapping TS_BIGINT setter
	 */
	public void setTsBigint(java.lang.Long value) {
		setValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.TS_BIGINT, value);
	}
	
	/**
	 * mapping TS_BIGINT getter
	 */
	public java.lang.Long getTsBigint() {
		return getValue(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES.TS_BIGINT);
	}
	
//MP-MANAGED-UPDATABLE-ENDING

	/**
	 * Create a detached TDatesRecord
	 */
	public TDatesRecord() {
		super(org.jooq.mp.hsqldb.test.tables.TDates.__T_DATES);
	}

//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@

}
