
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.mysql.test.tables;

import org.jooq.mp.mysql.test.tables.records.TIdentityPkRecord;
import org.jooq.mp.mysql.test.Test;
import org.jooq.mp.mysql.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class TIdentityPk extends org.jooq.impl.UpdatableTableImpl <TIdentityPkRecord> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of TIdentityPk
	 */
	public static final TIdentityPk __T_IDENTITY_PK = new TIdentityPk();

	/**
	 * The class holding records for this type
	 */
	private static final Class<TIdentityPkRecord> __RECORD_TYPE = TIdentityPkRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TIdentityPkRecord> getRecordType() {
		return __RECORD_TYPE;
	}


 
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY id
	 */
	public final TableField<TIdentityPkRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

 	/**
	 * VAL mapping for val
	 */
	public final TableField<TIdentityPkRecord, java.lang.Integer> VAL = createField("val", org.jooq.impl.SQLDataType.INTEGER, this);


	/**
	 * No further instances allowed
	 */
	private TIdentityPk() {
		super("t_identity_pk", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private TIdentityPk(String alias) {
		super(alias, Test.TEST, TIdentityPk.__T_IDENTITY_PK);
	}

	@Override
	public org.jooq.UniqueKey<TIdentityPkRecord> getMainKey() {
		return Keys.KEY_t_identity_pk_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<UniqueKey<TIdentityPkRecord>> getKeys() {
		return java.util.Arrays.<UniqueKey<TIdentityPkRecord>>asList(Keys.KEY_t_identity_pk_PRIMARY);
	}

	@Override
	public TIdentityPk as(java.lang.String alias) {
		return new TIdentityPk(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
