
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.mysql.test.tables;

import org.jooq.mp.mysql.test.tables.records.VLibraryRecord;
import org.jooq.mp.mysql.test.Test;
import org.jooq.mp.mysql.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class VLibrary extends org.jooq.impl.UpdatableTableImpl <VLibraryRecord> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of VLibrary
	 */
	public static final VLibrary __V_LIBRARY = new VLibrary();

	/**
	 * The class holding records for this type
	 */
	private static final Class<VLibraryRecord> __RECORD_TYPE = VLibraryRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VLibraryRecord> getRecordType() {
		return __RECORD_TYPE;
	}



 	/**
	 * AUTHOR mapping for AUTHOR
	 */
	public final TableField<VLibraryRecord, java.lang.String> AUTHOR = createField("AUTHOR", org.jooq.impl.SQLDataType.VARCHAR, this);
 	/**
	 * TITLE mapping for TITLE
	 */
	public final TableField<VLibraryRecord, java.lang.String> TITLE = createField("TITLE", org.jooq.impl.SQLDataType.LONGVARCHAR, this);


	/**
	 * No further instances allowed
	 */
	private VLibrary() {
		super("v_library", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private VLibrary(String alias) {
		super(alias, Test.TEST, VLibrary.__V_LIBRARY);
	}

	@Override
	public VLibrary as(java.lang.String alias) {
		return new VLibrary(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
