
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.hsqldb.test.tables;

import org.jooq.mp.hsqldb.test.tables.records.T65832Record;
import org.jooq.mp.hsqldb.test.Test;
import org.jooq.mp.hsqldb.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class T65832 extends org.jooq.impl.UpdatableTableImpl <T65832Record> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of T65832
	 */
	public static final T65832 __T_658_32 = new T65832();

	/**
	 * The class holding records for this type
	 */
	private static final Class<T65832Record> __RECORD_TYPE = T65832Record.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<T65832Record> getRecordType() {
		return __RECORD_TYPE;
	}


 
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY ID
	 */
	public final TableField<T65832Record, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT, this);

 	/**
	 * CD mapping for CD
	 */
	public final TableField<T65832Record, java.lang.Long> CD = createField("CD", org.jooq.impl.SQLDataType.BIGINT, this);


	/**
	 * No further instances allowed
	 */
	private T65832() {
		super("T_658_32", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private T65832(String alias) {
		super(alias, Test.TEST, T65832.__T_658_32);
	}

	@Override
	public org.jooq.UniqueKey<T65832Record> getMainKey() {
		return Keys.KEY_t_658_32_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<UniqueKey<T65832Record>> getKeys() {
		return java.util.Arrays.<UniqueKey<T65832Record>>asList(Keys.KEY_t_658_32_PRIMARY);
	}

	@Override
	public T65832 as(java.lang.String alias) {
		return new T65832(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
