
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.hsqldb.test.tables;

import org.jooq.mp.hsqldb.test.tables.records.T937Record;
import org.jooq.mp.hsqldb.test.Test;
import org.jooq.mp.hsqldb.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class T937 extends org.jooq.impl.UpdatableTableImpl <T937Record> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of T937
	 */
	public static final T937 __T_937 = new T937();

	/**
	 * The class holding records for this type
	 */
	private static final Class<T937Record> __RECORD_TYPE = T937Record.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<T937Record> getRecordType() {
		return __RECORD_TYPE;
	}


 
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY T_937
	 */
	public final TableField<T937Record, java.lang.Integer> ID = createField("T_937", org.jooq.impl.SQLDataType.INTEGER, this);



	/**
	 * No further instances allowed
	 */
	private T937() {
		super("T_937", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private T937(String alias) {
		super(alias, Test.TEST, T937.__T_937);
	}

	@Override
	public org.jooq.UniqueKey<T937Record> getMainKey() {
		return Keys.KEY_t_937_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<UniqueKey<T937Record>> getKeys() {
		return java.util.Arrays.<UniqueKey<T937Record>>asList(Keys.KEY_t_937_PRIMARY);
	}

	@Override
	public T937 as(java.lang.String alias) {
		return new T937(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
