
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.hsqldb.test.tables;

import org.jooq.mp.hsqldb.test.tables.records.TTriggersRecord;
import org.jooq.mp.hsqldb.test.Test;
import org.jooq.mp.hsqldb.test.Keys;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import java.util.List;
import java.util.Arrays;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class TTriggers extends org.jooq.impl.UpdatableTableImpl <TTriggersRecord> {

	private static final long serialVersionUID = 123456789;

	/**
	 * The singleton instance of TTriggers
	 */
	public static final TTriggers __T_TRIGGERS = new TTriggers();

	/**
	 * The class holding records for this type
	 */
	private static final Class<TTriggersRecord> __RECORD_TYPE = TTriggersRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TTriggersRecord> getRecordType() {
		return __RECORD_TYPE;
	}


 
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY ID_GENERATED
	 */
	public final TableField<TTriggersRecord, java.lang.Integer> ID_GENERATED = createField("ID_GENERATED", org.jooq.impl.SQLDataType.INTEGER, this);

 	/**
	 * ID mapping for ID
	 */
	public final TableField<TTriggersRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);
 	/**
	 * COUNTER mapping for COUNTER
	 */
	public final TableField<TTriggersRecord, java.lang.Integer> COUNTER = createField("COUNTER", org.jooq.impl.SQLDataType.INTEGER, this);


	/**
	 * No further instances allowed
	 */
	private TTriggers() {
		super("T_TRIGGERS", Test.TEST);
	}

	/**
	 * No further instances allowed
	 */
	private TTriggers(String alias) {
		super(alias, Test.TEST, TTriggers.__T_TRIGGERS);
	}

	@Override
	public org.jooq.UniqueKey<TTriggersRecord> getMainKey() {
		return Keys.KEY_t_triggers_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<UniqueKey<TTriggersRecord>> getKeys() {
		return java.util.Arrays.<UniqueKey<TTriggersRecord>>asList(Keys.KEY_t_triggers_PRIMARY);
	}

	@Override
	public TTriggers as(java.lang.String alias) {
		return new TTriggers(alias);
	}
	
//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@	

}
