
/**
 * This class is generated by minuteproject 4 jOOQ
 */
package org.jooq.mp.derby.test.tables.records;

import org.jooq.impl.UpdatableRecordImpl;

import org.jooq.mp.derby.test.tables.TIdentityPk;
import org.jooq.mp.derby.test.Test;
import org.jooq.mp.derby.test.Keys;
import java.sql.*;

//MP-MANAGED-ADDED-AREA-BEGINNING @import@
//MP-MANAGED-ADDED-AREA-ENDING @import@

//MP-MANAGED-ADDED-AREA-BEGINNING @class-annotation@
//MP-MANAGED-ADDED-AREA-ENDING @class-annotation@
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.4"},
                            comments = "This class is generated by minuteproject 4 jOOQ")
public class TIdentityPkRecord extends UpdatableRecordImpl<org.jooq.mp.derby.test.tables.records.TIdentityPkRecord> {

	private static final long serialVersionUID = 123456789;

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-pk-test@
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public void setId(java.lang.Integer value) {
        setValue(org.jooq.mp.derby.test.tables.TIdentityPk.__T_IDENTITY_PK.ID, value);
    }
	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
    public java.lang.Integer getId() {
        return getValue(org.jooq.mp.derby.test.tables.TIdentityPk.__T_IDENTITY_PK.ID);
    }
//MP-MANAGED-UPDATABLE-ENDING
//many2many

 //MP-MANAGED-UPDATABLE-BEGINNING-DISABLE @jooq-record-attribute-org.jooq.mp.derby.test.tables.TIdentityPk.__T_IDENTITY_PK.VAL-test@
	/**
	 * mapping VAL setter
	 */
	public void setVal(java.lang.Integer value) {
		setValue(org.jooq.mp.derby.test.tables.TIdentityPk.__T_IDENTITY_PK.VAL, value);
	}
	
	/**
	 * mapping VAL getter
	 */
	public java.lang.Integer getVal() {
		return getValue(org.jooq.mp.derby.test.tables.TIdentityPk.__T_IDENTITY_PK.VAL);
	}
	
//MP-MANAGED-UPDATABLE-ENDING

	/**
	 * Create a detached TIdentityPkRecord
	 */
	public TIdentityPkRecord() {
		super(org.jooq.mp.derby.test.tables.TIdentityPk.__T_IDENTITY_PK);
	}

//MP-MANAGED-ADDED-AREA-BEGINNING @implementation@
//MP-MANAGED-ADDED-AREA-ENDING @implementation@

}
